[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "wolsocketproxy"
version = "0.2.0"
description = "A socket proxy with wake-on-lan feature."
authors = [
    {name = "Song Fuchang", email = "song.fc@gmail.com"}
]
license = "Apache-2.0"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Topic :: System :: Networking"
]
requires-python = ">=3.12"
dependencies = [
    "aiohttp==3.13.5",
    "dataclass-wizard==0.39.1",
    "icmplib==3.0.4",
    "redfish==3.3.5",
    "wakeonlan==3.1.0",
]

[project.optional-dependencies]
dev = [
    "wolsocketproxy[lint]",
    "wolsocketproxy[build]",
]
lint = [
    "ty",
    "ruff",
]
build = [
    "build[virtualenv]==1.4.2",
]

[project.urls]
source = "https://github.com/notsyncing/wolsocketproxy"
issues = "https://github.com/notsyncing/wol-socket-proxy/issues"

[project.scripts]
wolsocketproxy = "wolsocketproxy:main"

[tool.ruff]
line-length = 120
src = ["src"]
target-version = "py312"
lint.select = ["ALL"]
lint.ignore = [
    "COM812",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D107",
    "D203",
    "D211",
    "D213",
    "S101",
    "EM102",
    "FBT001",
    "FBT003",
    "ISC001",
    "TRY003",
    "TRY201",
]
