version: '3.1'

services:
  wolsocketproxy:
    image: ghcr.io/notsyncing/wol-socket-proxy:main
    volumes:
      # Put your config file here, named wolsocketproxy.conf
      - /mnt/data/wolsocketproxy/config:/app/config:Z
    restart: always
    # Only host network can forward wol packets
    network_mode: host

